### ISSUE TITLE
Why call updateCalculatedFields() and save() ?

### ISSUE THREAD

**Issue by karlingen** [blak3r/sugarcrm-update-calculated-fields#4]
Why is there an call to updateCalculatedFields() when this is already being called when running save() on the bean?

**Comment by blak3r** [comment]
To be honest... I'm not sure.  I think you might be right... it's probably unnecessary.
My initial commit didn't appear to have it.

@bickart, any ideas?

**Comment by bickart** [comment]
Depends on the version of SugarCRM. In older versions it didn't get called properly. But I think that has been fixed for a while

**Comment by karlingen** [comment]
https://github.com/blak3r/sugarcrm-update-calculated-fields/pull/5
